version: "3.9"

networks:
  resto-net:
    driver: bridge

volumes:
  restaurant-db-data:
  payment-db-data:
  kafka-data:
  redis-data:

services:
  postgres-restaurant:
    image: postgres:16.6
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: ${RESTAURANT_DB_NAME}
      POSTGRES_USER: ${RESTAURANT_DB_USER}
      POSTGRES_PASSWORD: ${RESTAURANT_DB_PASSWORD}
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - resto-net

  postgres-payment:
    image: postgres:16.6
    container_name: postgres-payment
    environment:
      POSTGRES_DB: ${PAYMENT_DB_NAME}
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - resto-net

  redis:
    image: redis:7
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - resto-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - resto-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SET_ACL: "false"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - resto-net

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    depends_on:
      - postgres-restaurant
      - redis
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RESTAURANT_DB_HOST: postgres-restaurant
      RESTAURANT_DB_PORT: 5432
      RESTAURANT_DB_NAME: ${RESTAURANT_DB_NAME}
      RESTAURANT_DB_USER: ${RESTAURANT_DB_USER}
      RESTAURANT_DB_PASSWORD: ${RESTAURANT_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      RESTAURANT_SERVICE_CLIENT_ID: ${RESTAURANT_SERVICE_CLIENT_ID}
      RESTAURANT_SERVICE_CLIENT_SECRET: ${RESTAURANT_SERVICE_CLIENT_SECRET}

    ports:
      - "8080:8080"
    networks:
      - resto-net
  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - postgres-payment
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PAYMENT_DB_HOST: postgres-payment
      PAYMENT_DB_PORT: 5432
      PAYMENT_DB_NAME: ${PAYMENT_DB_NAME}
      PAYMENT_DB_USER: ${PAYMENT_DB_USER}
      PAYMENT_DB_PASSWORD: ${PAYMENT_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      DB_PASSWORD: ${PAYMENT_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
    ports:
      - "8081:8080"
    networks:
      - resto-net

  auth-utility-service:
    build: ./auth-utility-service
    container_name: auth-utility-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}

      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_CLIENT_SECRET: ${ADMIN_CLIENT_SECRET}

      STAFF_CLIENT_ID: ${STAFF_CLIENT_ID}
      STAFF_CLIENT_SECRET: ${STAFF_CLIENT_SECRET}

      RESTAURANT_SERVICE_CLIENT_ID: ${RESTAURANT_SERVICE_CLIENT_ID}
      RESTAURANT_SERVICE_CLIENT_SECRET: ${RESTAURANT_SERVICE_CLIENT_SECRET}

      CUSTOMER_CLIENT_ID: ${CUSTOMER_CLIENT_ID}
      CUSTOMER_CLIENT_SECRET: ${CUSTOMER_CLIENT_SECRET}

    ports:
      - "9000:8080"
    networks:
      - resto-net
