version: "3.9"

networks:
  resto-net:
    driver: bridge

volumes:
  restaurant-db-data:
  payment-db-data:
  kafka-data:
  redis-data:

services:
  postgres-restaurant:
    image: postgres:15
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: ${RESTAURANT_DB_NAME}
      POSTGRES_USER: ${RESTAURANT_DB_USER}
      POSTGRES_PASSWORD: ${RESTAURANT_DB_PASSWORD}
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - resto-net

  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    environment:
      POSTGRES_DB: ${PAYMENT_DB_NAME}
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - resto-net

  redis:
    image: redis:7
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
      --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* +@all
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - resto-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - resto-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # SASL/PLAIN
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN

      # JAAS config
      KAFKA_OPTS: >
        -Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./infra/kafka/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
    networks:
      - resto-net
